<a href="https://colab.research.google.com/github/UtkarshGupta12/Churn_Modelling/blob/master/Churn_Modelling(Dropout).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np 
import pandas as pd 

In [0]:
import keras

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/UtkarshGupta12/Churn_Modelling/master/Churn_Modelling.csv')

In [193]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
import matplotlib.pyplot as plt

In [0]:
df2 = df
df2 = df2.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [196]:
df2.head()

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [0]:
X = df.iloc[ : , 3:13].values
y = df.iloc[ : ,13].values

In [198]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[ : , 1]=labelencoder_X_1.fit_transform(X[ : , 1])
labelencoder_X_2 = LabelEncoder()
X[ : , 2]=labelencoder_X_2.fit_transform(X[ : , 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[ : , 1:]

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [199]:
X.shape

(10000, 11)

In [200]:
y.shape

(10000,)

In [0]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2 , random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [0]:
classifier = Sequential()

In [205]:
print(keras.__version__)

2.2.4


In [206]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
classifier.add(Dropout(p =0.1))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dropout(p =0.1))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  
W0726 11:05:51.664500 140186097137536 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  """


In [0]:
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [0]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics = ['accuracy'])

In [209]:
classifier.fit(X_train,y_train,batch_size=10,nb_epoch=100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
8000/8000 [==============================] - 1s 165us/step - loss: 0.5218 - acc: 0.7956
Epoch 2/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4424 - acc: 0.8144
Epoch 3/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4265 - acc: 0.8207
Epoch 4/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.4205 - acc: 0.8242
Epoch 5/100
8000/8000 [==============================] - 1s 134us/step - loss: 0.4210 - acc: 0.8216
Epoch 6/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.4184 - acc: 0.8231
Epoch 7/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.4129 - acc: 0.8210
Epoch 8/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.4101 - acc: 0.8230
Epoch 9/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.4110 - acc: 0.8234
Epoch 10/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4095 - acc: 0.8222

In [0]:
y_pred = classifier.predict(X_test)

In [211]:
y_pred

array([[0.25160086],
       [0.19182554],
       [0.14722088],
       ...,
       [0.19881526],
       [0.14334387],
       [0.17713481]], dtype=float32)

In [0]:
y_pred = (y_pred > 0.5 )

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [214]:
cm

array([[1545,   50],
       [ 240,  165]])

In [218]:
(1545+165)/2000

0.855

In [0]:
new_prediction = classifier.predict(sc.transform(np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])))

In [217]:
new_prediction =( new_prediction > 0.5 )
new_prediction

array([[False]])